# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Neo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "TextFieldEffects"
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod "PromiseKit", "~> 6.0"
  pod 'PromiseKit/Alamofire'
  pod 'Socket.IO-Client-Swift', '~> 13.2.0'
  pod 'XLPagerTabStrip', '~> 8.0'
  pod 'TransitionButton'
  pod 'RAMAnimatedTabBarController'
  pod 'GoogleWebRTC'

  # Pods for Neo

  target 'NeoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
